### ISSUE TITLE
Please give me push rights to this repo

### ISSUE THREAD

**Issue by rfk** [mozilla/picl-oldsync#1]
Hrmm, I transferred this repo from my personal github over to mozilla, and now I don't have access rights.  @warner or @ckarlof do you guys have sufficient privs to adjust the ownership settings on this repo to match the other picl-related repos?

**Comment by ckarlof** [comment]
@warner does, I don't.

**Comment by warner** [comment]
I think you should be good now, I added the "identity" (github) team.

**Comment by rfk** [comment]
verified fixed :-)  thanks!

/me makes a note not to use the "transfer repo" functionality in future...
